name: Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest